name: sube
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  provider: ^4.1.2
  fl_chart: ^0.9.4
  mapbox_gl: ^0.7.0
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-sube.png"

flutter_launcher_name:
  name: "SUBE"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
